const LocalStorage = {
  USER_ID: 'USER_ID',
  USER_USERNAME: 'USER_USERNAME',
  USER_AVATAR: 'USER_AVATAR',
  USER_EMAIL: 'USER_EMAIL',

  FARM_ID: 'FARM_ID',
  FARM_ACTIVE: 'FARM_ACTIVE',
  FARM_ACTIVE_EMAIL: 'FARM_ACTIVE_EMAIL',

  FIRST_ACCESS_TOKEN: 'FIRST_ACCESS_TOKEN',
  FIRST_REFRESH_TOKEN: 'FIRST_REFRESH_TOKEN',
  FIRST_TOKEN_EXPIRES_IN: 'FIRST_TOKEN_EXPIRES_IN',
  IS_FIRST_LOGIN: 'IS_FIRST_LOGIN',

  SECOND_ACCESS_TOKEN: 'SECOND_ACCESS_TOKEN',
  SECOND_REFRESH_TOKEN: 'SECOND_REFRESH_TOKEN',
  SECOND_TOKEN_EXPIRES_IN: 'SECOND_TOKEN_EXPIRES_IN',
  IS_SECOND_LOGIN: 'IS_SECOND_LOGIN',
};

export default LocalStorage;
